name: deploy-api

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checks-out repository under $GITHUB_WORKSPACE, so the workflow job can access it
            - name: Checkout
              uses: actions/checkout@v4

            # Deploys the API to the server
            - name: Deploy API
              env:
                  DEPLOY_URL: ${{ secrets.DEPLOY_HOOK_URL }}
              run: |
                  curl "$DEPLOY_URL"
